name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Configure CI Git User
        run: |
          git config --global user.name '@procode2'
          git config --global user.email 'iamprobablycoding@gmail.com'
          git remote set-url origin https://$GITHUB_ACTOR:$REPO_PAT@github.com/procode2/monorepo-test
        env:
          GITHUB_PAT: ${{ secrets.REPO_PAT }}
      - name: Checkout and pull branch
        run: git checkout "${GITHUB_REF:11}" && git pull
      - name: Install Packages
        run: yarn install
      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@procode2:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Change access of package to public
      - run: npm config set access public
      - name: Publish package
        run: npm run deploy:lerna
        env:
          GH_TOKEN: ${{ secrets.REPO_PAT }}
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
